AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Resources:
  GoServerlesSamFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./main
      Policies:
        DynamoDBCrudPolicy:
          TableName: go-serverles-dynamo
      Handler: main
      Runtime: go1.x
      Architectures:
        - x86_64
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /stagging
            Method: ANY