version: '3'

services:
  keycloak-login:
    image: quay.io/keycloak/keycloak:25.0.0
    depends_on:
      - postgres-db
    container_name: keycloak
    ports:
      - "8080:8080"
    command:
      - start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres-db/test-keycloak
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: root
      KC_HOSTNAME: localhost
  postgres-db:
    image: postgres:15.4-alpine3.18
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: test-keycloak
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - ~/.local/data/pgsql_15.4-alpine3.18/:/var/lib/postgresql/data
  application:
    depends_on:
      - postgres-db
      - keycloak-login
    build: .
    container_name: test-keycloack
    environment:
      CLIENT_ID: rips-backend-credentials
      CLIENT_SECRET: AwAbIXzg9P7XbWJBe3NeYJ2vG9up0dHK
      REALM: rips-back-local
      USER_ADMIN: admin
      PWD_ADMIN: admin
      REALM_ADMIN: master
      KEYCLOAK_URL: http://keycloak-login:8080
