version: '3.1'

services:
  postgre_db:
    image: postgres:12.9-alpine
    container_name: postgre_zabud
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - ~/.local/data/pgsql:/var/lib/postgresql/data

  web:
    build: .
    container_name: flask-api-test
    depends_on:
      - postgre_db
    volumes:
      - ./src:/usr/src/app
    ports:
      - "5000:5000"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: flask_db
      POSTGRES_PASSWORD: root
      POSTGRE_URL: postgre_db